# Generated by Django 5.2.3 on 2025-06-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
